import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Product from 'App/Models/Product'

export default class ProductsSeeder extends BaseSeeder {
  public async run() {
    await Product.createMany([
      {
        id: 1,
        name: 'Fresh Organic Apples',
        description: 'Locally grown organic apples, fresh and delicious.',
        stock_quantity: 100,
        units_sold: 50,
        price: 5,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 1,
        category_id: 1,
      },
      {
        id: 2,
        name: 'Grass-Fed Beef Steak',
        description: 'Premium quality grass-fed beef steak, tender and juicy.',
        stock_quantity: 50,
        units_sold: 25,
        price: 15,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 2,
        category_id: 2,
      },
      {
        id: 3,
        name: 'Freshly Harvested Tomatoes',
        description: 'Vine-ripened tomatoes, picked fresh from the farm.',
        stock_quantity: 80,
        units_sold: 40,
        price: 3,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 3,
        category_id: 3,
      },
      {
        id: 4,
        name: 'Handcrafted Goat Cheese',
        description: 'Artisanal goat cheese, crafted with care and expertise.',
        stock_quantity: 60,
        units_sold: 30,
        price: 8,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 4,
        category_id: 4,
      },
      {
        id: 5,
        name: 'Freshly Baked Artisan Bread',
        description: 'Handcrafted artisan bread, baked daily for maximum freshness.',
        stock_quantity: 120,
        units_sold: 60,
        price: 6,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 5,
        category_id: 5,
      },
      {
        id: 6,
        name: 'Organic Free-Range Eggs',
        description: 'Farm-fresh organic eggs from free-range chickens.',
        stock_quantity: 200,
        units_sold: 100,
        price: 4,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 6,
        category_id: 6,
      },
      {
        id: 7,
        name: 'Fresh Wild-Caught Salmon',
        description: 'Wild-caught salmon, sourced sustainably from pristine waters.',
        stock_quantity: 40,
        units_sold: 20,
        price: 12,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 7,
        category_id: 7,
      },
      {
        id: 8,
        name: 'Handpicked Organic Strawberries',
        description: 'Juicy and sweet organic strawberries, handpicked with care.',
        stock_quantity: 150,
        units_sold: 75,
        price: 7,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 8,
        category_id: 8,
      },
      {
        id: 9,
        name: 'Artisanal Honey from Local Beekeepers',
        description: 'Pure and natural honey, harvested by local beekeepers.',
        stock_quantity: 100,
        units_sold: 50,
        price: 10,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 9,
        category_id: 9,
      },
      {
        id: 10,
        name: 'Organic Kale & Spinach Mix',
        description: 'Fresh and nutritious blend of organic kale and spinach.',
        stock_quantity: 80,
        units_sold: 40,
        price: 4,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 10,
        category_id: 10,
      },
      {
        id: 11,
        name: 'Handcrafted Soy Candles',
        description: 'Eco-friendly soy candles, handcrafted with natural fragrances.',
        stock_quantity: 50,
        units_sold: 25,
        price: 12,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 11,
        category_id: 11,
      },
      {
        id: 12,
        name: 'Organic Lavender Essential Oil',
        description: 'Pure organic lavender essential oil, perfect for aromatherapy.',
        stock_quantity: 30,
        units_sold: 15,
        price: 18,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 9,
        category_id: 9,
      },
      {
        id: 13,
        name: 'Handcrafted Wooden Cutting Board',
        description: 'Beautifully handcrafted wooden cutting board, made from sustainable wood.',
        stock_quantity: 70,
        units_sold: 35,
        price: 20,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 8,
        category_id: 8,
      },
      {
        id: 15,
        name: 'Handcrafted Ceramic Mug Set',
        description: 'Artisanal ceramic mug set, perfect for enjoying your favorite beverages.',
        stock_quantity: 60,
        units_sold: 30,
        price: 25,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 7,
        category_id: 7,
      },
      {
        id: 16,
        name: 'Organic Quinoa Grain',
        description: 'Nutrient-rich organic quinoa grain, perfect for healthy meals.',
        stock_quantity: 100,
        units_sold: 50,
        price: 7,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 6,
        category_id: 6,
      },
      {
        id: 17,
        name: 'Handwoven Cotton Throw Blanket',
        description: 'Soft and cozy handwoven cotton throw blanket, perfect for chilly nights.',
        stock_quantity: 80,
        units_sold: 40,
        price: 30,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 5,
        category_id: 5,
      },
      {
        id: 18,
        name: 'Organic Lavender Hand Soap',
        description: 'Gentle and nourishing organic lavender hand soap, soothes and moisturizes.',
        stock_quantity: 120,
        units_sold: 60,
        price: 6,
        image_url: 'https://loremflickr.com/640/480/abstract',
        seller_id: 4,
        category_id: 4,
      },
    ])
  }
}
