import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Order from 'App/Models/Orders'

export default class OrderSeeder extends BaseSeeder {
  public async run() {
    await Order.createMany([
      {
        buyer_id: 1,
        seller_id: 1,
        product_id: 3,
        quantity: 7,
        total_price: 125,
        status: 'pending',
        payment_method: 'credit_card',
        payment_transaction_id: 4587,
        comments: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        delivery_address: '123 Main Street',
        tracking_number: 987654,
      },
      {
        buyer_id: 2,
        seller_id: 1,
        product_id: 1,
        quantity: 5,
        total_price: 200,
        status: 'shipped',
        payment_method: 'cash_on_delivery',
        payment_transaction_id: 3256,
        comments:
          'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.',
        delivery_address: '456 Elm Street',
        tracking_number: 123456,
      },
      {
        buyer_id: 3,
        seller_id: 1,
        product_id: 2,
        quantity: 3,
        total_price: 50,
        status: 'delivered',
        payment_method: 'bank_transfer',
        payment_transaction_id: 6548,
        comments:
          'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.',
        delivery_address: '789 Oak Street',
        tracking_number: 789012,
      },
      {
        buyer_id: 4,
        seller_id: 3,
        product_id: 4,
        quantity: 2,
        total_price: 75,
        status: 'canceled',
        payment_method: 'paypal',
        payment_transaction_id: 7896,
        comments: 'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.',
        delivery_address: '1011 Pine Street',
        tracking_number: 345678,
      },
      {
        buyer_id: 5,
        seller_id: 3,
        product_id: 5,
        quantity: 4,
        total_price: 100,
        status: 'pending',
        payment_method: 'credit_card',
        payment_transaction_id: 1596,
        comments: 'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.',
        delivery_address: '1213 Cedar Street',
        tracking_number: 234567,
      },
      {
        buyer_id: 6,
        seller_id: 3,
        product_id: 6,
        quantity: 1,
        total_price: 30,
        status: 'shipped',
        payment_method: 'cash_on_delivery',
        payment_transaction_id: 3579,
        comments:
          'Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam.',
        delivery_address: '1415 Birch Street',
        tracking_number: 890123,
      },
      {
        buyer_id: 7,
        seller_id: 5,
        product_id: 7,
        quantity: 6,
        total_price: 150,
        status: 'delivered',
        payment_method: 'bank_transfer',
        payment_transaction_id: 2468,
        comments:
          'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
        delivery_address: '1617 Maple Street',
        tracking_number: 456789,
      },
      {
        buyer_id: 8,
        seller_id: 5,
        product_id: 8,
        quantity: 3,
        total_price: 90,
        status: 'pending',
        payment_method: 'paypal',
        payment_transaction_id: 1357,
        comments:
          'Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.',
        delivery_address: '1819 Oak Street',
        tracking_number: 567890,
      },
      {
        buyer_id: 9,
        seller_id: 5,
        product_id: 9,
        quantity: 2,
        total_price: 60,
        status: 'shipped',
        payment_method: 'credit_card',
        payment_transaction_id: 2468,
        comments:
          'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.',
        delivery_address: '2021 Cedar Street',
        tracking_number: 123789,
      },
    ])
  }
}
